### ISSUE TITLE
ssl error on connection

### ISSUE THREAD

**Issue by defaliz** [vshymanskyy/blynk-library-python#56]
hi, 
i use the script example 01_virtual_write.py on my local server on a pi zero
with the code 
blynk = BlynkLib.Blynk(BLYNK_AUTH, server='x.x.x.x', port=8080)
And i have the error below.. i don't know why because i use the same code on another pizero whitout error..
can you help ?
best regards
Alain

Connecting to x.x.x.x:8080...
Traceback (most recent call last):
  File "01_virtual_write.py", line 19, in <module>
    blynk = BlynkLib.Blynk(BLYNK_AUTH, server='13.59.253.251', port=8080)
  File "build/bdist.linux-armv6l/egg/BlynkLib.py", line 214, in __init__
  File "build/bdist.linux-armv6l/egg/BlynkLib.py", line 81, in __init__
  File "build/bdist.linux-armv6l/egg/BlynkLib.py", line 240, in connect
  File "/usr/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
socket.error: [Errno 0] Error

**Comment by Un-ka** [comment]
Change port `BlynkLib.Blynk(BLYNK_AUTH, server='x.x.x.x', port=443)`

**Comment by defaliz** [comment]
great un-ka !
that works now..
regards
